import { Question } from '@/types/quiz';

export const QUESTIONS: Question[] = [
  {
    id: 'n01',
    number: 1,
    category: 'Vibes',
    text: "Okay Nesrine… let's start easy 👀\nWhat's the kind of day that instantly puts you in a good mood?",
    type: 'single-choice',
    options: [
      { id: 'cozy', label: 'A slow cozy day', emoji: '☕' },
      { id: 'new', label: 'Going somewhere new', emoji: '✈️' },
      { id: 'food', label: 'Good food + good company', emoji: '🍝' },
      { id: 'unexpected', label: 'A day full of little unexpected moments', emoji: '✨' },
    ],
    weight: 1,
    scorable: true,
  },
  {
    id: 'n02',
    number: 2,
    category: 'Vibes',
    text: "Very important scientific question:\nWhat can you never say no to? 😂",
    type: 'single-choice',
    options: [
      { id: 'food', label: 'Good food', emoji: '🍕' },
      { id: 'surprise', label: 'A cute little surprise', emoji: '🎁' },
      { id: 'convo', label: 'A really good conversation', emoji: '💬' },
      { id: 'go', label: '"Come on, let\'s go somewhere" 👀', emoji: '🏃‍♀️' },
    ],
    weight: 1,
    scorable: true,
  },
  {
    id: 'n03',
    number: 3,
    category: 'Connection',
    text: "When you really like someone, what's the thing you notice first?",
    type: 'single-choice',
    transitionMessage: "Okay, I wasn't expecting that 😂",
    options: [
      { id: 'smile', label: 'Their smile', emoji: '✨' },
      { id: 'eyes', label: 'Their eyes', emoji: '👁️' },
      { id: 'humor', label: 'Their sense of humor', emoji: '😂' },
      { id: 'treat', label: 'The way they treat people', emoji: '💙' },
    ],
    weight: 1.5,
    scorable: true,
  },
  {
    id: 'n04',
    number: 4,
    category: 'Memories',
    text: "Be honest… do you actually enjoy taking pictures, or are you more of a \"take 97 pictures and keep 2\" person? 😂📸",
    image: '/Taking Pics.jpg',
    type: 'single-choice',
    options: [
      { id: 'love', label: 'I LOVE taking pictures', emoji: '📸' },
      { id: 'special', label: 'Only when the moment is special', emoji: '✨' },
      { id: '97to2', label: 'I\'m definitely the "97 → 2" person 😂', emoji: '😅' },
      { id: 'others', label: 'I usually end up in someone else\'s pictures', emoji: '🤷‍♀️' },
    ],
    weight: 1,
    scorable: true,
  },
  {
    id: 'n05',
    number: 5,
    category: 'Us',
    text: "What's your idea of a genuinely nice date?",
    type: 'single-choice',
    transitionMessage: "Noted… very important information. 👀",
    options: [
      { id: 'dinner', label: 'Dinner somewhere beautiful', emoji: '✨' },
      { id: 'coffee', label: 'Coffee + walking + talking', emoji: '☕' },
      { id: 'spontaneous', label: 'Doing something completely spontaneous', emoji: '🚀' },
      { id: 'quiet', label: 'Somewhere quiet where we can just enjoy each other\'s company', emoji: '🤍' },
    ],
    weight: 1.5,
    scorable: true,
  },
  {
    id: 'n06',
    number: 6,
    category: 'Vibes',
    text: "Which tiny thing can make you ridiculously happy?",
    type: 'single-choice',
    options: [
      { id: 'remembering', label: 'Someone remembering something I said', emoji: '💭' },
      { id: 'reminded', label: 'A random "this reminded me of you" message', emoji: '💌' },
      { id: 'food', label: 'Unexpected food 😂', emoji: '🍔' },
      { id: 'hug', label: 'A really good hug', emoji: '🤗' },
      { id: 'other', label: 'Other / little things', emoji: '✨' },
    ],
    weight: 1.5,
    scorable: true,
  },
  {
    id: 'n07',
    number: 7,
    category: 'Personality',
    text: "Nesrine, be honest… What's your relationship with compliments? 😂",
    type: 'single-choice',
    options: [
      { id: 'love', label: 'I secretly love them', emoji: '🤭' },
      { id: 'pretend', label: 'I\'ll pretend I don\'t care', emoji: '😌' },
      { id: 'genuine', label: 'Only when they\'re genuine', emoji: '🎯' },
      { id: 'laugh', label: 'Make me laugh first, compliment me later', emoji: '😂' },
    ],
    weight: 1,
    scorable: true,
  },
  {
    id: 'n08',
    number: 8,
    category: 'Connection',
    text: "Pick the kind of conversation you could accidentally stay up until 3 AM having:",
    type: 'single-choice',
    options: [
      { id: 'deep', label: 'Deep life conversations', emoji: '🌌' },
      { id: 'stupid', label: 'Completely stupid conversations 😂', emoji: '🤪' },
      { id: 'childhood', label: 'Stories from childhood', emoji: '🧸' },
      { id: 'travel', label: '"What if we just left and travelled somewhere?" conversations', emoji: '✈️' },
    ],
    weight: 1.5,
    scorable: true,
  },
  {
    id: 'n09',
    number: 9,
    category: 'Connection',
    text: "What makes someone instantly more attractive to you?",
    type: 'single-choice',
    transitionMessage: "We're learning things now. 😌",
    options: [
      { id: 'kind', label: 'Being genuinely kind', emoji: '💙' },
      { id: 'funny', label: 'Being funny', emoji: '😂' },
      { id: 'confidence', label: 'Having confidence', emoji: '😎' },
      { id: 'attention', label: 'Giving people their full attention', emoji: '👁️' },
      { id: 'cantexplain', label: 'Having that little something you can\'t really explain 👀', emoji: '✨' },
    ],
    weight: 1.5,
    scorable: true,
  },
  {
    id: 'n10',
    number: 10,
    category: 'Us',
    text: "Imagine we have one completely free day. What sounds the most fun?",
    type: 'single-choice',
    options: [
      { id: 'explore', label: 'Explore a new place', emoji: '🗺️' },
      { id: 'food', label: 'Food, coffee and walking around', emoji: '🚶‍♀️' },
      { id: 'stayin', label: 'Stay in and watch things all day', emoji: '🎬' },
      { id: 'noplan', label: 'Start with no plan and see where we end up 😂', emoji: '🎲' },
    ],
    weight: 1.5,
    scorable: true,
  },
  {
    id: 'n11',
    number: 11,
    category: 'Personality',
    text: "What's something your friends would absolutely expose you for? 😂",
    type: 'single-choice',
    options: [
      { id: 'overthinking', label: 'Overthinking', emoji: '🤔' },
      { id: 'stubborn', label: 'Being stubborn', emoji: '😤' },
      { id: 'pictures', label: 'Taking too many pictures', emoji: '📸' },
      { id: 'laughing', label: 'Laughing at the worst possible moment', emoji: '🫢' },
      { id: 'other', label: 'Something else', emoji: '🤷‍♀️' },
    ],
    weight: 1,
    scorable: true,
  },
  {
    id: 'n12',
    number: 12,
    category: 'Us',
    text: "Who has the most beautiful smile in the world?",
    image: '/Smile.webp',
    imageNote: "Btw… I already picked Nesrine 😌",
    type: 'single-choice',
    transitionMessage: "Okay, this one says a lot 😌",
    options: [
      { id: 'nesrine', label: 'Nesrine 💘', emoji: '✨' },
      { id: 'emma', label: 'Emma', emoji: '👩' },
      { id: 'lina', label: 'Lina', emoji: '👩‍🦰' },
      { id: 'sofia', label: 'Sofia', emoji: '👱‍♀️' },
      { id: 'maya', label: 'Maya', emoji: '👧' },
    ],
    weight: 1.5,
    scorable: true,
  },
  {
    id: 'n13',
    number: 13,
    category: 'Connection',
    text: "What's your favorite kind of affection?",
    type: 'single-choice',
    options: [
      { id: 'hugs', label: 'Long hugs', emoji: '🤍' },
      { id: 'hands', label: 'Holding hands', emoji: '🤝' },
      { id: 'gestures', label: 'Little thoughtful gestures', emoji: '🎁' },
      { id: 'teasing', label: 'Teasing each other 😂', emoji: '😜' },
      { id: 'mixture', label: 'A mixture of everything', emoji: '✨' },
    ],
    weight: 1.5,
    scorable: true,
  },
  {
    id: 'n14',
    number: 14,
    category: 'Vibes',
    text: "What's more your kind of happiness?",
    type: 'single-choice',
    options: [
      { id: 'sunset', label: 'A beautiful sunset', emoji: '🌅' },
      { id: 'meal', label: 'A really good meal', emoji: '🍝' },
      { id: 'adventure', label: 'A spontaneous adventure', emoji: '🚀' },
      { id: 'conversation', label: 'A long conversation with someone I love', emoji: '💬' },
    ],
    weight: 1,
    scorable: true,
  },
  {
    id: 'n15',
    number: 15,
    category: 'Connection',
    text: "What makes you feel that someone genuinely cares about you?",
    type: 'single-choice',
    options: [
      { id: 'remember', label: 'They remember the little things', emoji: '💭' },
      { id: 'checkin', label: 'They check in without a reason', emoji: '📱' },
      { id: 'time', label: 'They make time for me', emoji: '⏱️' },
      { id: 'notice', label: 'They notice when something is wrong', emoji: '🥺' },
    ],
    weight: 1.5,
    scorable: true,
  },
  {
    id: 'n16',
    number: 16,
    category: 'Us',
    text: "Okay, one honest one 👀\nWould you rather have someone who makes you laugh constantly or someone who always makes you feel safe and understood?",
    type: 'single-choice',
    transitionMessage: "You're making this surprisingly difficult 😂",
    options: [
      { id: 'laugh', label: 'Make me laugh', emoji: '😂' },
      { id: 'safe', label: 'Make me feel safe', emoji: '🤍' },
      { id: 'both', label: 'Both… obviously', emoji: '✨' },
      { id: 'depends', label: 'Depends on the person', emoji: '🤷‍♀️' },
    ],
    weight: 1.5,
    scorable: true,
  },
  {
    id: 'n17',
    number: 17,
    category: 'Vibes',
    text: "What's a place you'd happily disappear to for a few days?",
    type: 'single-choice',
    options: [
      { id: 'beach', label: 'A beach somewhere warm', emoji: '🌊' },
      { id: 'city', label: 'A beautiful European city', emoji: '🏛️' },
      { id: 'nature', label: 'Somewhere surrounded by nature', emoji: '🌲' },
      { id: 'hidden', label: 'Somewhere nobody can find me 😂', emoji: '👻' },
    ],
    weight: 1,
    scorable: true,
  },
  {
    id: 'n18',
    number: 18,
    category: 'Connection',
    text: "Pick a tiny moment that feels more romantic than a big fancy gesture:",
    type: 'single-choice',
    options: [
      { id: 'walking', label: 'Walking together with no destination', emoji: '🚶‍♀️' },
      { id: 'favorite', label: 'Someone remembering your favorite thing', emoji: '🎁' },
      { id: 'laughing', label: 'Laughing together over something stupid', emoji: '😂' },
      { id: 'quiet', label: 'Sitting quietly together and feeling completely comfortable', emoji: '🤍' },
    ],
    weight: 1.5,
    scorable: true,
  },
  {
    id: 'n19',
    number: 19,
    category: 'Us',
    text: "Alright… dangerous question 😌\nWhat do you think makes two people actually click?",
    type: 'single-choice',
    transitionMessage: "One more…",
    options: [
      { id: 'personality', label: 'Similar personalities', emoji: '👯‍♀️' },
      { id: 'humor', label: 'Similar sense of humor', emoji: '😂' },
      { id: 'comfortable', label: 'Feeling comfortable around each other', emoji: '😌' },
      { id: 'different', label: 'Being different in the right ways', emoji: '🧩' },
      { id: 'know', label: 'You just know', emoji: '✨' },
    ],
    weight: 1.5,
    scorable: true,
  },
  {
    id: 'n20',
    number: 20,
    category: 'Us',
    text: "Last one, Nesrine…\nDo you think two people can meet and just naturally feel like they've known each other for much longer? 👀",
    type: 'single-choice',
    options: [
      { id: 'definitely', label: 'Definitely', emoji: '🤍' },
      { id: 'maybe', label: 'Maybe', emoji: '🤔' },
      { id: 'depends', label: 'It depends', emoji: '🤷‍♀️' },
      { id: 'interesting', label: 'Hmm… interesting question', emoji: '😌' },
    ],
    weight: 2,
    scorable: true,
  },
];

export const TOTAL_QUESTIONS = QUESTIONS.length;
