import { Question } from '@/types/quiz';

export const QUESTIONS: Question[] = [
  // ── EVERYDAY LIFE ──────────────────────────────────────────────
  {
    id: 'q01',
    number: 1,
    category: 'Everyday Life',
    text: 'Morning person or night owl?',
    emoji: '🌅',
    type: 'single-choice',
    options: [
      { id: 'morning', label: 'Morning person', emoji: '☀️' },
      { id: 'night', label: 'Night owl', emoji: '🦉' },
      { id: 'neither', label: 'Neither — I exist in the void', emoji: '💀' },
      { id: 'both', label: 'Depends on the day', emoji: '🤷' },
    ],
    weight: 1,
    scorable: true,
  },
  {
    id: 'q02',
    number: 2,
    category: 'Everyday Life',
    text: 'Coffee or tea?',
    emoji: '☕',
    type: 'single-choice',
    options: [
      { id: 'coffee', label: 'Coffee, obviously', emoji: '☕' },
      { id: 'tea', label: 'Tea, always', emoji: '🍵' },
      { id: 'both', label: 'Both — I have no limits', emoji: '😈' },
      { id: 'neither', label: 'Neither — water supremacy', emoji: '💧' },
    ],
    weight: 0.5,
    scorable: true,
  },
  {
    id: 'q03',
    number: 3,
    category: 'Everyday Life',
    text: 'Stay in or go out?',
    emoji: '🏡',
    type: 'single-choice',
    options: [
      { id: 'stayin', label: 'Stay in — comfort is life', emoji: '🛋️' },
      { id: 'goout', label: 'Go out — I need to be perceived', emoji: '🌆' },
      { id: 'depends', label: "Depends who's asking 👀", emoji: '👀' },
      { id: 'both', label: 'Both, equally', emoji: '⚖️' },
    ],
    weight: 1,
    scorable: true,
  },
  {
    id: 'q04',
    number: 4,
    category: 'Everyday Life',
    text: 'Plan everything or improvise?',
    emoji: '📅',
    type: 'single-choice',
    options: [
      { id: 'plan', label: 'Plan everything', emoji: '📋' },
      { id: 'improvise', label: 'Improvise — structure is a myth', emoji: '🌀' },
      { id: 'hybrid', label: 'Plan loosely, improvise wildly', emoji: '🎲' },
      { id: 'depends', label: 'Depends on the situation', emoji: '🤔' },
    ],
    weight: 1.5,
    scorable: true,
  },
  {
    id: 'q05',
    number: 5,
    category: 'Everyday Life',
    text: 'Texting or voice notes?',
    emoji: '📱',
    type: 'single-choice',
    options: [
      { id: 'text', label: 'Texting — voice notes are chaos', emoji: '💬' },
      { id: 'voice', label: 'Voice notes — I have things to say', emoji: '🎙️' },
      { id: 'both', label: 'Both — I contain multitudes', emoji: '✨' },
      { id: 'call', label: 'Neither — just call me', emoji: '📞' },
    ],
    weight: 0.5,
    scorable: true,
  },
  {
    id: 'q06',
    number: 6,
    category: 'Everyday Life',
    text: 'Summer or winter?',
    emoji: '🌞',
    type: 'single-choice',
    options: [
      { id: 'summer', label: 'Summer — sun, always', emoji: '☀️' },
      { id: 'winter', label: 'Winter — cozy season', emoji: '❄️' },
      { id: 'spring', label: 'Spring/Autumn — the sane choice', emoji: '🍂' },
      { id: 'neither', label: 'I hate all weather', emoji: '😭' },
    ],
    weight: 0.5,
    scorable: true,
  },
  {
    id: 'q07',
    number: 7,
    category: 'Everyday Life',
    text: 'Organized or controlled chaos?',
    emoji: '🗂️',
    type: 'single-choice',
    options: [
      { id: 'organized', label: 'Organized — a place for everything', emoji: '🗂️' },
      { id: 'chaos', label: 'Controlled chaos — I know where everything is', emoji: '🌪️' },
      { id: 'pretend', label: 'I pretend to be organized', emoji: '🙂' },
      { id: 'neither', label: 'Pure chaos, no control', emoji: '💥' },
    ],
    weight: 1,
    scorable: true,
  },

  // ── FOOD ───────────────────────────────────────────────────────
  {
    id: 'q08',
    number: 8,
    category: 'Food',
    text: 'Sweet or salty?',
    emoji: '🍩',
    type: 'single-choice',
    options: [
      { id: 'sweet', label: 'Sweet — dessert is life', emoji: '🍩' },
      { id: 'salty', label: 'Salty — chips > cake', emoji: '🥨' },
      { id: 'both', label: 'Both — sweet AND salty is peak', emoji: '🍫' },
      { id: 'neither', label: 'I just eat for fuel', emoji: '🤖' },
    ],
    weight: 0.5,
    scorable: true,
  },
  {
    id: 'q09',
    number: 9,
    category: 'Food',
    text: 'Spicy food — love it or regret it?',
    emoji: '🌶️',
    type: 'single-choice',
    options: [
      { id: 'love', label: 'Love it — the spicier the better', emoji: '🔥' },
      { id: 'medium', label: 'Medium — I like a little kick', emoji: '🌶️' },
      { id: 'regret', label: 'Regret it every time but keep trying', emoji: '😂' },
      { id: 'no', label: 'Absolutely not', emoji: '🚫' },
    ],
    weight: 0.5,
    scorable: true,
  },
  {
    id: 'q10',
    number: 10,
    category: 'Food',
    text: 'Ideal comfort food?',
    emoji: '🍕',
    type: 'single-choice',
    options: [
      { id: 'pizza', label: 'Pizza', emoji: '🍕' },
      { id: 'pasta', label: 'Pasta', emoji: '🍝' },
      { id: 'ramen', label: 'Ramen / noodles', emoji: '🍜' },
      { id: 'other', label: 'Something custom / other', emoji: '😏' },
    ],
    weight: 0.5,
    scorable: true,
  },
  {
    id: 'q11',
    number: 11,
    category: 'Food',
    text: 'Breakfast person or absolutely not?',
    emoji: '🥞',
    type: 'single-choice',
    options: [
      { id: 'yes', label: "Yes — breakfast is sacred", emoji: '🥞' },
      { id: 'sometimes', label: "Sometimes, when I'm functional", emoji: '😴' },
      { id: 'no', label: 'Absolutely not — food starts at noon', emoji: '🚫' },
      { id: 'coffee', label: 'Coffee counts as breakfast', emoji: '☕' },
    ],
    weight: 0.5,
    scorable: true,
  },
  {
    id: 'q12',
    number: 12,
    category: 'Food',
    text: 'Try something weird or play it safe?',
    emoji: '🧪',
    type: 'single-choice',
    options: [
      { id: 'weird', label: 'Try something weird — life is short', emoji: '🧪' },
      { id: 'safe', label: 'Play it safe — I know what I like', emoji: '🛡️' },
      { id: 'depends', label: 'Depends on my mood', emoji: '🎭' },
      { id: 'watch', label: "I'll watch YOU try it first", emoji: '👀' },
    ],
    weight: 1,
    scorable: true,
  },

  // ── SOCIAL ─────────────────────────────────────────────────────
  {
    id: 'q13',
    number: 13,
    category: 'Social',
    text: 'Big group or small group?',
    emoji: '👥',
    type: 'single-choice',
    options: [
      { id: 'big', label: 'Big group — the more the merrier', emoji: '🎉' },
      { id: 'small', label: 'Small group — quality over quantity', emoji: '✨' },
      { id: 'one', label: 'One-on-one is ideal', emoji: '💬' },
      { id: 'alone', label: 'Can I just stay home?', emoji: '🏠' },
    ],
    weight: 1.5,
    scorable: true,
  },
  {
    id: 'q14',
    number: 14,
    category: 'Social',
    text: 'Party or cozy evening?',
    emoji: '🎊',
    type: 'single-choice',
    options: [
      { id: 'party', label: "Party — let's go", emoji: '🎊' },
      { id: 'cozy', label: 'Cozy evening — blankets + vibes', emoji: '🕯️' },
      { id: 'depends', label: "Depends on the week I've had", emoji: '🤷' },
      { id: 'both', label: 'Party for 2 hours then leave', emoji: '😂' },
    ],
    weight: 1,
    scorable: true,
  },
  {
    id: 'q15',
    number: 15,
    category: 'Social',
    text: 'Talk all night or comfortable silence?',
    emoji: '💬',
    type: 'single-choice',
    options: [
      { id: 'talk', label: 'Talk all night — I have opinions', emoji: '💬' },
      { id: 'silence', label: 'Comfortable silence is everything', emoji: '🤫' },
      { id: 'both', label: 'Both — balance is key', emoji: '⚖️' },
      { id: 'depends', label: 'Depends on the person', emoji: '😌' },
    ],
    weight: 1.5,
    scorable: true,
  },
  {
    id: 'q16',
    number: 16,
    category: 'Social',
    text: 'Spontaneous adventure or planned trip?',
    emoji: '🗺️',
    type: 'single-choice',
    options: [
      { id: 'spontaneous', label: "Spontaneous — let's just go", emoji: '🚀' },
      { id: 'planned', label: 'Planned — I need to know the hotel', emoji: '📋' },
      { id: 'hybrid', label: 'Plan the basics, wing the rest', emoji: '🗺️' },
      { id: 'neither', label: 'Can we stay home instead?', emoji: '🛋️' },
    ],
    weight: 1,
    scorable: true,
  },

  // ── TRAVEL ─────────────────────────────────────────────────────
  {
    id: 'q17',
    number: 17,
    category: 'Travel',
    text: 'Beach or mountains?',
    emoji: '🌊',
    type: 'single-choice',
    options: [
      { id: 'beach', label: 'Beach — sun, sand, vibes', emoji: '🌊' },
      { id: 'mountains', label: 'Mountains — fresh air, peace', emoji: '🏔️' },
      { id: 'city', label: 'Neither — city breaks only', emoji: '🏙️' },
      { id: 'both', label: 'Both — I contain contradictions', emoji: '✨' },
    ],
    weight: 1,
    scorable: true,
  },
  {
    id: 'q18',
    number: 18,
    category: 'Travel',
    text: 'City trip or peaceful getaway?',
    emoji: '✈️',
    type: 'single-choice',
    options: [
      { id: 'city', label: 'City trip — explore everything', emoji: '🏙️' },
      { id: 'peaceful', label: 'Peaceful getaway — I need quiet', emoji: '🌿' },
      { id: 'mix', label: 'Mix of both', emoji: '🎯' },
      { id: 'anywhere', label: 'Anywhere with good food', emoji: '🍽️' },
    ],
    weight: 1,
    scorable: true,
  },

  // ── PERSONALITY ────────────────────────────────────────────────
  {
    id: 'q19',
    number: 19,
    category: 'Personality',
    text: 'What makes you laugh fastest?',
    emoji: '😂',
    type: 'single-choice',
    options: [
      { id: 'sarcasm', label: 'Dry wit / sarcasm', emoji: '🧂' },
      { id: 'physical', label: 'Silly physical comedy', emoji: '🤪' },
      { id: 'absurd', label: 'Absurd / chaotic energy', emoji: '🌀' },
      { id: 'relate', label: 'Painfully relatable jokes', emoji: '😭' },
    ],
    weight: 1,
    scorable: true,
  },
  {
    id: 'q20',
    number: 20,
    category: 'Personality',
    text: 'What instantly annoys you?',
    emoji: '😤',
    type: 'single-choice',
    options: [
      { id: 'slow', label: 'People walking slowly in front of me', emoji: '🚶' },
      { id: 'late', label: 'People being chronically late', emoji: '⏰' },
      { id: 'loud', label: 'Unnecessary loud noises', emoji: '📢' },
      { id: 'flaky', label: 'People who cancel last minute', emoji: '👻' },
    ],
    weight: 1,
    scorable: true,
  },
  {
    id: 'q21',
    number: 21,
    category: 'Personality',
    text: 'What would your friends roast you for?',
    emoji: '🔥',
    type: 'single-choice',
    options: [
      { id: 'late', label: 'Always being late', emoji: '😬' },
      { id: 'overthink', label: 'Overthinking everything', emoji: '🤯' },
      { id: 'forget', label: 'Forgetting to reply to messages', emoji: '💀' },
      { id: 'stubborn', label: 'Being weirdly stubborn', emoji: '😤' },
    ],
    weight: 0.5,
    scorable: true,
  },
  {
    id: 'q22',
    number: 22,
    category: 'Personality',
    text: 'One thing you could never live without?',
    emoji: '💙',
    type: 'single-choice',
    options: [
      { id: 'music', label: 'Music', emoji: '🎵' },
      { id: 'phone', label: 'My phone (yes, I said it)', emoji: '📱' },
      { id: 'people', label: 'My close people', emoji: '🫂' },
      { id: 'alone', label: 'Alone time to recharge', emoji: '🔋' },
    ],
    weight: 1,
    scorable: true,
  },

  // ── RELATIONSHIPS ──────────────────────────────────────────────
  {
    id: 'q23',
    number: 23,
    category: 'Relationships',
    text: 'What makes you feel most appreciated?',
    emoji: '🫶',
    type: 'single-choice',
    options: [
      { id: 'words', label: 'Kind words / compliments', emoji: '💬' },
      { id: 'time', label: 'Quality time together', emoji: '⏱️' },
      { id: 'acts', label: 'Small thoughtful acts', emoji: '🎁' },
      { id: 'touch', label: 'Physical affection', emoji: '🤗' },
    ],
    weight: 1.5,
    scorable: true,
  },
  {
    id: 'q24',
    number: 24,
    category: 'Relationships',
    text: 'Ideal date?',
    emoji: '💑',
    type: 'single-choice',
    options: [
      { id: 'fancy', label: 'Fancy dinner', emoji: '🍾' },
      { id: 'coffee', label: 'Coffee + long walk', emoji: '☕' },
      { id: 'adventure', label: 'Adventure / activity', emoji: '🏄' },
      { id: 'stayin', label: 'Staying in together', emoji: '🎬' },
    ],
    weight: 1.5,
    scorable: true,
  },
  {
    id: 'q25',
    number: 25,
    category: 'Relationships',
    text: 'What wins you over fastest?',
    emoji: '💘',
    type: 'single-choice',
    options: [
      { id: 'humor', label: 'Making me laugh', emoji: '😂' },
      { id: 'depth', label: 'Deep conversations', emoji: '🌊' },
      { id: 'effort', label: 'Effort and consistency', emoji: '💪' },
      { id: 'vibe', label: "Just the vibe, can't explain it", emoji: '✨' },
    ],
    weight: 1.5,
    scorable: true,
  },
  {
    id: 'q26',
    number: 26,
    category: 'Relationships',
    text: 'How important is communication?',
    emoji: '📡',
    type: 'single-choice',
    options: [
      { id: 'everything', label: 'Everything — I need to talk things out', emoji: '💬' },
      { id: 'very', label: 'Very important but I struggle with it', emoji: '😅' },
      { id: 'actions', label: 'Important, but actions matter more', emoji: '🎯' },
      { id: 'moderate', label: 'Moderately — some things stay unsaid', emoji: '🤐' },
    ],
    weight: 1.5,
    scorable: true,
  },
  {
    id: 'q27',
    number: 27,
    category: 'Relationships',
    text: 'Instant turn-off?',
    emoji: '🚩',
    type: 'single-choice',
    options: [
      { id: 'rude', label: 'Rude to service staff', emoji: '🚩' },
      { id: 'ego', label: 'Massive ego / arrogance', emoji: '💅' },
      { id: 'flaky', label: 'Being flaky / unreliable', emoji: '👻' },
      { id: 'nohumor', label: 'No sense of humor', emoji: '😐' },
    ],
    weight: 1.5,
    scorable: true,
  },

  // ── CUTE / CHEEKY ──────────────────────────────────────────────
  {
    id: 'q28',
    number: 28,
    category: 'Cute & Cheeky',
    text: 'Choose your weapon of affection',
    emoji: '🤍',
    type: 'single-choice',
    options: [
      { id: 'hugs', label: 'Long hugs', emoji: '🤗' },
      { id: 'forehead', label: 'Forehead kisses', emoji: '😚' },
      { id: 'teasing', label: 'Playful teasing', emoji: '😜' },
      { id: 'hands', label: 'Hand holding', emoji: '🤝' },
    ],
    weight: 1,
    scorable: true,
  },
  {
    id: 'q29',
    number: 29,
    category: 'Cute & Cheeky',
    text: 'Who gets attached first?',
    emoji: '🥺',
    type: 'single-choice',
    options: [
      { id: 'me', label: 'Me, obviously 😭', emoji: '😭' },
      { id: 'them', label: "Them — I'm a menace", emoji: '😈' },
      { id: 'both', label: 'We both fall simultaneously', emoji: '🥺' },
      { id: 'nobody', label: "Nobody — we're both emotionally unavailable 😂", emoji: '💀' },
    ],
    weight: 1,
    scorable: true,
  },
  {
    id: 'q30',
    number: 30,
    category: 'Cute & Cheeky',
    text: 'What makes someone instantly more attractive?',
    emoji: '😍',
    type: 'single-choice',
    options: [
      { id: 'humor', label: 'A great sense of humor', emoji: '😂' },
      { id: 'kindness', label: 'Genuine kindness', emoji: '💙' },
      { id: 'confidence', label: 'Quiet confidence', emoji: '😎' },
      { id: 'attention', label: 'Paying real attention', emoji: '👁️' },
    ],
    weight: 1.5,
    scorable: true,
  },
];

export const TOTAL_QUESTIONS = QUESTIONS.length;
